frameworkVersion: "2"

org: cinthialandia
app: udacity-final-project
service: udacity-final-project-backend

plugins:
  - serverless-webpack
  - serverless-iam-roles-per-function
  - serverless-plugin-tracing

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: "20201221"

  # https://www.serverless.com/framework/docs/deprecations/#PARAMETERIZED_ARGUMENT
  # You may override values in serverless.yml for stage and region with command line arguments --stage and --region
  stage: "dev"
  region: "us-east-1"

  tracing:
    lambda: true
    apiGateway: true

  logs:
    # Enable API Gateway logs
    restApi: true

  iamRoleStatements:
    - Effect: Allow
      Action:
        - xray:PutTelemetryRecords
        - xray:PutTraceSegments
      Resource: "*"

  environment:
    ANSWERS_TABLE: Answers-${self:provider.stage}

functions:
  Auth:
    handler: src/lambda/auth/auth0Authorizer.handler

  Hello:
    handler: src/lambda/hello.handler
    events:
      - http:
          path: /
          method: get
          cors: true
          authorizer: Auth

  GetAnswers:
    handler: src/lambda/http/getAnswers.handler
    events:
      - http:
          method: get
          path: answers/{questionId}
          cors: true
          authorizer: Auth
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:DescribeTable
          - dynamodb:GetItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.ANSWERS_TABLE}

resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: "AWS::ApiGateway::GatewayResponse"
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: "ApiGatewayRestApi"

    AnswersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: questionId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: questionId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.ANSWERS_TABLE}
